In [1]:
import numpy as np
a=np.array([1,2,3])

In [2]:
print(a.shape)

(3,)


In [4]:
b=np.array([[1,2],[2,3]])

In [5]:
print(b.shape)

(2, 2)


In [6]:
a[0]

1

In [11]:
print(a[1],a[0])

2 1


In [13]:
a=np.array([[1,2,3],[2,3,4],[2,3,4]])

In [14]:
print(a)

[[1 2 3]
 [2 3 4]
 [2 3 4]]


In [15]:
b=a[1:3,1:3]
print(b)

[[3 4]
 [3 4]]


In [19]:
b[1,1]=30 #impact also on a

In [17]:
print(b)

[[ 3  4]
 [ 3 30]]


In [18]:
print(a)

[[ 1  2  3]
 [ 2  3  4]
 [ 2  3 30]]


In [3]:
import pandas as pd
s=pd.Series([11,12,13,14],index=[1,2,3,4])

In [31]:
s

1    11
2    12
3    13
4    14
dtype: int64

In [4]:
s=pd.Series(5,index=[1,2,3,4,5],dtype=(np.float16))

In [12]:
student=[('Ram',21),('Mohan',22)]
df=pd.DataFrame(student,columns=['Name','Age'])

In [10]:
print(df)

    Name  Age
0    Ram   21
1  Mohan   22


In [ ]:
data=pd.read_csv('file_name.csv',name=['Name','Age','Salary'])#method for access csv file

In [ ]:
print(data)

In [ ]:
data.head()#Print Top 5 record

In [ ]:
print(data.head(3))

In [ ]:
data.tail(3) #print from buttom

In [15]:
data=pd.read_excel('iris.xlsx',names=['sepal lenth','sepal width','petal lenth','petal width','spacies']) #method for access excel file 

ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.

In [ ]:
data=pd.read_csv('ddata.tsv',names=['Name','Age','Salary'],sep='\t')

In [ ]:
data['Name'] #only Name  

In [ ]:
data[['Name'],['Age']]

In [ ]:
data.iloc[2:5,1:3]