In [1]:
import numpy as np

In [2]:
student=np.dtype([('name','S20'),('age','i4'),('marks','f4')])

In [3]:
type(student)

numpy.dtype

In [4]:
s1=np.array([('Ramandeep singh gurjewala',21,67)],dtype=student)

In [5]:
print(s1)

[(b'Ramandeep singh gurj', 21, 67.)]


In [6]:
a1=np.arange(1,13,1)

In [7]:
print(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
m1=a1.reshape(4,3)

In [10]:
print(m1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
m1[2,2]

9

In [13]:
m1[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [52]:
print(m1.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [15]:
print(m1.mean())

6.5


In [16]:
print(np.zeros([3,3]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
print(np.ones([3,3]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [55]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
m1=np.arange(1,10,1).reshape(3,3)
m2=np.arange(2,20,2).reshape(3,3)
print(m1)
print(m2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [24]:
m3=np.dot(m1,m2) #for crose multiplicaton of two matrix

In [25]:
print(m3)

[[ 60  72  84]
 [132 162 192]
 [204 252 300]]


In [26]:
print(np.add(m1,m2))  # for addition of two matrix

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [28]:
print(np.subtract(m1,m2)) #for subtraction of two matrix

[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]


In [29]:
print(np.divide(m2,m1))  #for division of two matrix

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [30]:
print(np.multiply(m1,m2)) #simple multiply of two matrix 

[[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]


In [31]:
m4=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [32]:
print(m4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
m4.size

9

In [34]:
m5=np.array([[1,2,3,4],[4,5,6,7],[9,5,8,6],[8,9,6,3]])

In [35]:
print(m5)

[[1 2 3 4]
 [4 5 6 7]
 [9 5 8 6]
 [8 9 6 3]]


In [45]:
m5[1:4,1:4]

array([[5, 6, 7],
       [5, 8, 6],
       [9, 6, 3]])

In [42]:
m5[1:3,1:3]

array([[5, 6],
       [5, 8]])

In [46]:
print(np.hsplit(m5,2))

[array([[1, 2],
       [4, 5],
       [9, 5],
       [8, 9]]), array([[3, 4],
       [6, 7],
       [8, 6],
       [6, 3]])]


In [50]:
print(np.vsplit(m5,2))

[array([[1, 2, 3, 4],
       [4, 5, 6, 7]]), array([[9, 5, 8, 6],
       [8, 9, 6, 3]])]


In [51]:
m5

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [9, 5, 8, 6],
       [8, 9, 6, 3]])